### ISSUE TITLE
error in demo 76 - in local method get_csv_by_table + get_table_by_csv

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5-samples#21]
![image](https://github.com/abap2UI5/abap2UI5-samples/assets/129428114/6a4b5414-0aaf-40ac-a5a9-3972f33a7723)

![image](https://github.com/abap2UI5/abap2UI5-samples/assets/129428114/ca5e6675-59ce-42a1-9d94-65ce0df6e3dc)

![image](https://github.com/abap2UI5/abap2UI5-samples/assets/129428114/50c4783e-6777-4ce9-b8dc-6fd2529c6579)

**Comment by oblomov-dev** [comment]
fixed with https://github.com/abap2UI5/abap2UI5-samples/commit/730f8107eb0a7b163b28849f1222759c0b990cfa

**Comment by choper725** [comment]
getting error in field symbol not assigned

![image](https://github.com/abap2UI5/abap2UI5-samples/assets/129428114/6bd7c6a4-5194-4430-aba6-e584b8a510d6)

**Comment by choper725** [comment]
also
