### ISSUE TITLE
error in demo 75

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5-samples#22]
![image](https://github.com/abap2UI5/abap2UI5-samples/assets/129428114/2d433b24-a15f-4381-835f-7ffc4355650f)

![image](https://github.com/abap2UI5/abap2UI5-samples/assets/129428114/d9ebf19c-383b-42ab-a0b6-c983f9f87445)

**Comment by oblomov-dev** [comment]
fixed with https://github.com/abap2UI5/abap2UI5-samples/commit/730f8107eb0a7b163b28849f1222759c0b990cfa
