### ISSUE TITLE
set_scroll_position in demo 00 not working

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5-samples#28]
hi @oblomov-dev 

recent change for set scroll position in demo 00, not working..
im not getting any error, its just not returning to previous scroll position when navigated back

**Comment by choper725** [comment]
it seems to work only when V is an integer
like this:
![image](https://github.com/abap2UI5/abap2UI5-samples/assets/129428114/eec3ff1f-6609-4a3f-a4fa-e49569fc0a58)


when its like this, its not scrolling to position
![image](https://github.com/abap2UI5/abap2UI5-samples/assets/129428114/71e9c1c9-936f-4368-addf-b71ff0d09c57)

**Comment by oblomov-dev** [comment]
i changed now the value transfer to integers. https://github.com/abap2UI5/abap2UI5/pull/450

I hope this solves also your problem. Can you check again?

**Comment by choper725** [comment]
working
