### ISSUE TITLE
demo 40 not working

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5-samples#34]
demo 40 not working
when loading the app:
![image](https://github.com/abap2UI5/abap2UI5-samples/assets/129428114/d2d0980a-cc47-42fd-8133-0a210cf14563

**Comment by oblomov-dev** [comment]
checked it and fixed it quickly:
<img width="819" alt="image" src="https://github.com/abap2UI5/abap2UI5-samples/assets/102328295/3f215ebb-929c-4ece-bbbd-f441521b5803">

but the demo looks a little bit outdated. when i will find time in the next days i will try to clean it up and make it easier to understand.

**Comment by choper725** [comment]
great thanks
