### ISSUE TITLE
Binding Error by Example 

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/abap2UI5-samples#45]
Hi @oblomov-dev,

i have bindung Errors by the Example 70,80, and 85.

BINDING_ERROR - No class attribute for binding found

How can i fix the Problem? 

Regards
Thomas

**Comment by oblomov-dev** [comment]
Install the latest tag and do not use the main branch. There are a few bugs I fix at the moment.

**Comment by oblomov-dev** [comment]
updated the demo repository. it is working again. 

changed the binding on some positions to bind_local for local variables.

**Comment by choper725** [comment]
we got new types of bindings now ??

**Comment by oblomov-dev** [comment]
no, but putting local variables in the _bind method create an error now and they are not binded automatically as local variables anymore. use bind_local instead as described here https://github.com/abap2UI5/abap2UI5/issues/512

i want to avoid unexpected behaviour with that.

**Comment by choper725** [comment]
good practice is to keep all variables public then ?

**Comment by oblomov-dev** [comment]
with _bind the value of your variable will be read in the end of the request, means you can also change this variable after you did the binding.

with _bind_local the variable is read at the moment of the method call. I use this for "static" variables as you can see here:
https://github.com/abap2UI5/abap2UI5-samples/blob/bd18947787536f0e4b8d462b2aa47c990f9a7842/src/z2ui5_cl_app_demo_02.clas.abap#L179

so it depends on what you want to do.

**Comment by choper725** [comment]
thanks for the explanation @oblomov-dev

**Comment by oblomov-dev** [comment]
both works!

i mostly use it directly on the property to make it obvious where it is used. but if you need it multiple time etc you can also assign it to a variable.

**Comment by Th0masMa** [comment]
everything works again.
Great works.
